# Generated by Django 2.2 on 2019-04-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.FloatField(default=0.0, verbose_name='がく片の長さ')),
                ('sepal_width', models.FloatField(default=0.0, verbose_name='がく片の幅')),
                ('petal_length', models.FloatField(default=0.0, verbose_name='花びらの長さ')),
                ('petal_width', models.FloatField(default=0.0, verbose_name='花びらの幅')),
                ('score', models.IntegerField(verbose_name='判定結果')),
            ],
        ),
    ]
